version: 0.2
env:
    variables:
        APP_NAME: "Gardner_Keeper"
        S3_BUCKET: "train.soma.farm"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}
            - echo Build completed on `date`

artifacts:
    files:
        - '*'
    discard-paths: yes
    base-directory: 'dist'